/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import enums.Sector;
import gestion.Inventario;
import modelo.empleados.Empleado;
import enums.Rol;
import javax.swing.JOptionPane;

/**
 *
 * @author inver
 */
public class CrearAdministradorFrame extends javax.swing.JFrame {
    
    private Inventario inventario;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearAdministradorFrame.class.getName());

    public CrearAdministradorFrame(Inventario inventario) {
        initComponents();
        this.inventario = inventario;
        cmbSector.removeAllItems();
        for (Sector sector : Sector.values()) {
            cmbSector.addItem(sector.name());
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearAdministrador = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        labelSector = new javax.swing.JLabel();
        cmbSector = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnCrearAdministrador = new javax.swing.JButton();
        btnCancelarCrearAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        crearAdministrador.setText("Primer Acceso");

        labelNombre.setText("Nombre");

        labelApellido.setText("Apellido");

        labelContrasena.setText("Contraseña");

        labelSector.setText("Sector");

        cmbSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSector.addActionListener(this::cmbSectorActionPerformed);

        btnCrearAdministrador.setText("Crear Administrador");
        btnCrearAdministrador.addActionListener(this::btnCrearAdministradorActionPerformed);

        btnCancelarCrearAdmin.setText("Cancelar");
        btnCancelarCrearAdmin.addActionListener(this::btnCancelarCrearAdminActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearAdministrador)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnCancelarCrearAdmin)
                        .addGap(37, 37, 37)))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crearAdministrador)
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addGap(34, 34, 34)
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelApellido)
                        .addGap(34, 34, 34)
                        .addComponent(txtApellido))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContrasena)
                            .addComponent(labelSector))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContrasena))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearAdministrador)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContrasena))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelSector)
                    .addComponent(cmbSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnCrearAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarCrearAdmin)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSectorActionPerformed

    private void btnCrearAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAdministradorActionPerformed
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String contrasena = new String(txtContrasena.getPassword());
        
        Sector sector = Sector.valueOf(cmbSector.getSelectedItem().toString());
        if (nombre.isEmpty() || apellido.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Complete todos los campos");
            return;
        }
        Empleado admin = new Empleado(inventario.generarLegajo(), nombre, apellido, sector, Rol.ADMINISTRADOR, contrasena);
        inventario.agregarEmpleado(admin);
        JOptionPane.showMessageDialog(this,"Administrador creado.\nLegajo: " + admin.getLegajo());
        dispose();
    }//GEN-LAST:event_btnCrearAdministradorActionPerformed

    private void btnCancelarCrearAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCrearAdminActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarCrearAdminActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCrearAdmin;
    private javax.swing.JButton btnCrearAdministrador;
    private javax.swing.JComboBox<String> cmbSector;
    private javax.swing.JLabel crearAdministrador;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSector;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
